# Generated by Django 5.0.7 on 2024-07-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PureOrganics', '0003_order_orderitem_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
    ]
