# Generated by Django 5.0.7 on 2024-07-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PureOrganics', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='PureOrganic_name_1119a2_idx'),
        ),
    ]
